#!/bin/bash

# TruthyFi Local Testing Script
# Automated setup for local testing and demos

set -e

echo "🚀 TruthyFi Local Testing Setup"
echo "================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if Foundry is installed
if ! command -v forge &> /dev/null; then
    echo -e "${RED}❌ Foundry not found!${NC}"
    echo "Install Foundry:"
    echo "  curl -L https://foundry.paradigm.xyz | bash"
    echo "  foundryup"
    exit 1
fi

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found!${NC}"
    echo "Install Node.js from https://nodejs.org/"
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites check passed${NC}"
echo ""

# Check if Anvil is already running
if lsof -Pi :8545 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    echo -e "${YELLOW}⚠️  Port 8545 is already in use${NC}"
    echo "Anvil may already be running or another service is using this port"
    read -p "Kill existing process and continue? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        kill -9 $(lsof -t -i:8545) 2>/dev/null || true
        sleep 2
    else
        echo "Exiting..."
        exit 1
    fi
fi

# Step 1: Start Anvil
echo -e "${BLUE}📦 Step 1: Starting local blockchain (Anvil)...${NC}"
anvil > /tmp/anvil.log 2>&1 &
ANVIL_PID=$!
echo "Anvil PID: $ANVIL_PID"
echo "Waiting for Anvil to start..."
sleep 3

# Verify Anvil is running
if ! kill -0 $ANVIL_PID 2>/dev/null; then
    echo -e "${RED}❌ Anvil failed to start${NC}"
    cat /tmp/anvil.log
    exit 1
fi

echo -e "${GREEN}✅ Anvil running on http://localhost:8545${NC}"
echo ""

# Default Anvil account
export PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
DEFAULT_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

echo -e "${BLUE}📝 Default Test Account:${NC}"
echo "  Address: $DEFAULT_ADDRESS"
echo "  Private Key: $PRIVATE_KEY"
echo ""

# Step 2: Build contracts
echo -e "${BLUE}🔨 Step 2: Building contracts...${NC}"
forge build > /dev/null 2>&1
echo -e "${GREEN}✅ Contracts built${NC}"
echo ""

# Step 3: Deploy contracts
echo -e "${BLUE}🚀 Step 3: Deploying contracts...${NC}"
forge script script/Deploy.s.sol:DeployScript \
  --rpc-url http://localhost:8545 \
  --broadcast \
  --silent

# Parse deployment addresses
if [ -f "deployments/31337.json" ]; then
    if command -v jq &> /dev/null; then
        export FACTORY_ADDRESS=$(jq -r '.factory' deployments/31337.json)
        export USDC_ADDRESS=$(jq -r '.usdc' deployments/31337.json)
    else
        # Fallback without jq
        export FACTORY_ADDRESS=$(grep -o '"factory": "[^"]*' deployments/31337.json | cut -d'"' -f4)
        export USDC_ADDRESS=$(grep -o '"usdc": "[^"]*' deployments/31337.json | cut -d'"' -f4)
    fi

    echo -e "${GREEN}✅ Contracts deployed${NC}"
    echo "  Factory: $FACTORY_ADDRESS"
    echo "  USDC: $USDC_ADDRESS"
    echo ""
else
    echo -e "${RED}❌ Deployment failed - no deployment file found${NC}"
    kill $ANVIL_PID
    exit 1
fi

# Step 4: Verify deployment
echo -e "${BLUE}✅ Step 4: Verifying deployment...${NC}"
forge script script/PostDeploymentCheck.s.sol:PostDeploymentCheck \
  --rpc-url http://localhost:8545 \
  2>&1 | grep -E "(✅|❌|ALL CHECKS)"

echo ""

# Step 5: Create demo markets
echo -e "${BLUE}📊 Step 5: Creating demo markets...${NC}"
forge script script/CreateDemoMarket.s.sol:CreateDemoMarket \
  --rpc-url http://localhost:8545 \
  --broadcast \
  --silent

echo -e "${GREEN}✅ Demo markets created${NC}"
echo ""

# Step 6: Test trading
echo -e "${BLUE}💰 Step 6: Testing trading functionality...${NC}"
forge script script/TestTrading.s.sol:TestTrading \
  --rpc-url http://localhost:8545 \
  --broadcast \
  --silent

echo -e "${GREEN}✅ Trading test passed${NC}"
echo ""

# Step 7: Frontend setup
echo -e "${BLUE}🌐 Step 7: Setting up frontend...${NC}"

if [ ! -d "frontend/node_modules" ]; then
    echo "Installing frontend dependencies (this may take a minute)..."
    cd frontend
    npm install --silent > /dev/null 2>&1
    cd ..
    echo -e "${GREEN}✅ Frontend dependencies installed${NC}"
else
    echo -e "${GREEN}✅ Frontend dependencies already installed${NC}"
fi

# Update frontend config
cat > frontend/src/config/contracts.local.ts << EOF
// Auto-generated by local-test.sh
export const LOCAL_CONTRACTS = {
  31337: {
    factory: '$FACTORY_ADDRESS',
    usdc: '$USDC_ADDRESS',
  },
}
EOF

echo -e "${GREEN}✅ Frontend configured${NC}"
echo ""

# Summary
echo "================================"
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "================================"
echo ""
echo -e "${BLUE}📋 Deployment Info:${NC}"
echo "  Network: Local (Anvil)"
echo "  Chain ID: 31337"
echo "  RPC URL: http://localhost:8545"
echo "  Factory: $FACTORY_ADDRESS"
echo "  USDC: $USDC_ADDRESS"
echo ""
echo -e "${BLUE}💼 Test Account:${NC}"
echo "  Address: $DEFAULT_ADDRESS"
echo "  Private Key: $PRIVATE_KEY"
echo "  Balance: 10,000 ETH + 1,000 USDC"
echo ""
echo -e "${BLUE}📊 Demo Markets:${NC}"
echo "  ✅ 5 prediction markets created"
echo "  ✅ Ready for trading"
echo ""
echo -e "${BLUE}🚀 Next Steps:${NC}"
echo ""
echo "1. Import test account to MetaMask:"
echo "   - Click MetaMask extension"
echo "   - Import Account → Private Key"
echo "   - Paste: $PRIVATE_KEY"
echo ""
echo "2. Add Local Network to MetaMask:"
echo "   - Network Name: Localhost"
echo "   - RPC URL: http://localhost:8545"
echo "   - Chain ID: 31337"
echo "   - Currency: ETH"
echo ""
echo "3. Start the frontend:"
echo "   cd frontend"
echo "   npm run dev"
echo ""
echo "4. Open http://localhost:3000"
echo ""
echo "5. Connect MetaMask and start trading!"
echo ""
echo -e "${YELLOW}📝 Useful Commands:${NC}"
echo "  View Anvil logs:     tail -f /tmp/anvil.log"
echo "  Monitor health:      forge script script/MonitorHealth.s.sol:MonitorHealth --rpc-url http://localhost:8545"
echo "  Get USDC:            cast send $USDC_ADDRESS 'faucet()' --rpc-url http://localhost:8545 --private-key \$PRIVATE_KEY"
echo "  Stop Anvil:          kill $ANVIL_PID"
echo ""
echo -e "${GREEN}Happy Testing! 🎉${NC}"
echo ""

# Save PID for cleanup
echo $ANVIL_PID > /tmp/truthy-anvil.pid
echo "Anvil PID saved to /tmp/truthy-anvil.pid"
echo ""
echo -e "${YELLOW}⚠️  Keep this terminal open or Anvil will stop${NC}"
echo -e "${YELLOW}   To stop Anvil: kill $ANVIL_PID${NC}"
echo ""

# Keep script running
wait $ANVIL_PID
